<?php require('template/header.phtml') ?>
<div class="row">
    <div class="col s12">
        <div id="test1" class="col s12">
            <div class="container">
                <form name="editUserForm" method="post" action="<?php echo $_SERVER['PHP_SELF']; ?>">
                    <div class="input-field col s12 l12">
                        <input type="text" name="userName" id="userName" value="<?php if (isset($_POST['userName'])){echo $_POST['userName'];} ?>" required>
                        <label for="userName">Username</label>
                    </div><br/>

                    <div class="right btn-block col s12 l12">
                        <input class="btn black right z-depth-2" type="submit" name="searchUser" value="Find Students">
                    </div>
                </form>
            </div>

            <?php
            if (isset($_POST['searchUser'])) {
                echo '<h6 class="center helper-text"><strong>Students</strong></h6>';
                echo '<div id="test1" class="col s12">
                <div class="container">';
                if (isset($view->teachersStudents)) {
                    if (empty($view->teachersStudents)) {
                        echo '<h6 class="center helper-text">There are no students</h6>';
                    } else {
                        //For every student in class
                        foreach ($view->teachersStudents as $student) {
                            $className = 'Error';
                            foreach ($view->allClasses as $class) {
                                if ($class->getClassID() == $student->getClassID()) {
                                    $className = $class->getClassName();
                                }
                            }
                            //One student
                            echo '<h6 class="helper-text">Username: ' . $student->getUserName() . ' Name: ' . $student->getFirstName() . ' ' . $student->getLastName() . ' Email: ' . $student->getEmail() . ' Class: ' . $className . '</h6>';
                        }
                    }
                }
                else{
                    echo '<h6 class="center helper-text">'. $view->error .'</h6>';
                }
            }
            echo '
            </div>
            </div>';
            ?>


        </div>
    </div>
</div>

<?php require('template/footer.phtml') ?>
