<?php require('template/header.phtml') ?>
<div class="container row" id="admin-container">
    <div class="container s12 l12" id="ls-header">
    </div>

    <div class="row">
        <div class="col s12">
            <div id="test1" class="col s12">
                <div class="container">
                    <form name="addUser" method="post" action="<?php echo $_SERVER['PHP_SELF']; ?>">
                        <div class="input-field col s12 l12">
                            <input type="text" name="userName" id="userName" value="<?php if (isset($_POST['userName'])){echo $_POST['userName'];} ?>" required>
                            <label for="userName">Username</label>
                        </div><br/>

                        <div class="right btn-block col s12 l12">
                            <input class="btn black right z-depth-2" type="submit" name="searchUser" value="Find User">
                        </div>
                    </form>
                </div


            </div>
        </div>
</div>
<?php require('template/footer.phtml') ?>
