<?php require('template/header.phtml') ?>
    <div class="container row s12 l12 rubric-admin">
        <div class="container z-depth-2 col s12 l12">
            <div class="col s12 l12" id="ls-header">
                <h6 class="center helper-text"><strong>Rubric Name</strong></h6>
            </div>
            <form name="table" method="post" action="<?php echo $_SERVER['PHP_SELF'];?>">
                <?php
                $rubrics = $view->rubric_count;
                while($rubrics > 0)
                {
                    echo "<div class=\"input-field col s6 offset-s3\">
                          <input id=\"r_name\" type=\"text\" name=\"{$rubrics}\" value=\"Name\" required>
                          </div>";

                    echo "<table class=\"fixed\">
                           <thead><tr><th>Category</th>";

                    $columns = $view->criteria_count;
                    while($columns > 0)
                    {
                        echo "<th>Criteria</th>";
                        $columns--;
                    }

                    echo "</thead></tr><tbody>";

                    $rows = $view->criteria_count_cols;
                    while($rows > 0)
                    {
                        echo "<tr>";
                        $rowTabs = $view->criteria_count+1;
                        $testCat = 1;
                        $testCrit = null;
                        while($rowTabs > 0)
                        {
                            echo "<td><div class=\"input-field col s12\">
                                  <textarea id=\"test\" class=\"materialize-textarea\" 
                                  name=\"{$rubrics}{$rows}{$rowTabs}\" required>";

                            //Test Delete
//                            if($testCat == 1)
//                            {
//                                echo "Cat{$testCat}";
//                            }
//                            else{
//                                echo "Crit{$testCrit}";
//                                 }
//                            $testCat++;
//                            $testCrit = $testCat-1;
                            //Test Delete

                            echo "</textarea>
                                  <label for=\"test\"></label>
                                  </div></td>";
                            $rowTabs--;
                        }
                        echo "</tr>";

                        $rows--;
                    }
                    echo"</tbody></table></br>";
                    $rubrics--;
                }
                ?>
                <div class="right btn-block col s12 l12">
                    <input class="btn black right z-depth-2" type="submit"
                           name="submit" value="Create" id="btn-under-alert">
                </div>
            </form>
        </div>
    </div>
<?php require('template/footer.phtml') ?>