<?php require('template/header.phtml') ?>
<div class="container row" id="admin-container">
    <div class="container s12 l12" id="ls-header">

    </div>

    <!--Container for all the content for the page-->
    <div class="container">
        <form name="firstName" method="post" action="<?php echo $_SERVER['PHP_SELF'];?>">
            <input type="text" name="firstName" id="firstName" required>
            <label for="firstName">Firstname</label>
        </form>
    </div></br>
</div>
<?php require('template/footer.phtml') ?>