<?php require('template/header.phtml') ?>
    <div class="container row s12 l12 rubric-admin">
        <div class="container col s12 l12">
            <form name="table" method="post" action="<?php echo $_SERVER['PHP_SELF'];?>">
                <?php
                $rubrics = $view->rubric_count;
                while($rubrics > 0)
                {
                    echo "<div class=\"input-field col s6 offset-s3\">
                          <input placeholder=\"Rubric Name\" id=\"r_name\" type=\"text\" name=\"{$rubrics}\" required>
                          </div>";

                    echo "<table class=\"fixed\">
                           <thead><tr><th>Category</th>";

                    $columns = $view->criteria_count;
                    while($columns > 0)
                    {
                        echo "<th>Criteria</th>";
                        $columns--;
                    }

                    echo "</thead></tr><tbody>";

                    $rows = $view->criteria_count_cols;
                    while($rows > 0)
                    {
                        echo "<tr>";
                        $rowTabs = $view->criteria_count+1;
                        while($rowTabs > 0)
                        {
                            echo "<td><div class=\"input-field col s12\">
                                  <textarea id=\"test\" class=\"materialize-textarea\" 
                                  name=\"{$rubrics}{$rows}{$rowTabs}\" required></textarea>
                                  <label for=\"test\">{$rubrics}{$rows}{$rowTabs}</label>
                                  </div></td>";
                            $rowTabs--;
                        }
                        echo "</tr>";

                        $rows--;
                    }
                    echo"</tbody></table></br>";
                    $rubrics--;
                }

//                $t=time();
//                $td = ($t . "<br>");
//                $tdb = (date("d-m-Y H:m:s",$t));
//                var_dump($tdb);
//
//                echo "<div class=\"input-field col s6 offset-s3\">
//                    <input id=\"r_name\" type=\"text\" name=\"date\" value\"{$tdb}\" hidden>
//                </div>";
                ?>



                <div class="right btn-block col s12 l12">
                    <input class="btn black right z-depth-2" type="submit"
                           name="submit" value="Create">
                </div>
            </form>
        </div>
    </div>
<?php require('template/footer.phtml') ?>