<?php require('template/header.phtml') ?>
<div class="container row" id="admin-container">
    <div class="container s12 l12" id="ls-header">
            <h6 class="center black-text"><strong>Edit User</strong></h6>
    </div>

    <div class="row">
        <div class="col s12">
            <div id="test1" class="col s12">
                <div class="container">
                    <form name="editUserForm" method="post" action="<?php echo $_SERVER['PHP_SELF']; ?>">
                        <div class="input-field col s12 l12">
                            <input type="text" name="userName" id="userName" value="<?php if (isset($_POST['userName'])){echo $_POST['userName'];} ?>" required>
                            <label for="userName">Username</label>
                        </div><br/>

                        <div class="right btn-block col s12 l12">
                            <input class="btn black right z-depth-2" type="submit" name="searchUser" value="Find User">
                        </div>
                    </form>
                </div>

                <div class="container">
                    <?php
                    if (isset($_POST['searchUser']))
                    {
                        if ($view->user!=null)
                        {
                            if ($view->user->getUsername() != null) {
                                if ($_SESSION['user']->getRoleID() != 1){
                                    if (($view->user->getRoleID() != 1) && ($_SESSION['user']->getClassID() == $view->user->getClassID()) && ($view->user->getRoleID() != 2)) {
                                        echo '
                                        <form name="addUser" method="post" action="' . $_SERVER['PHP_SELF'] . '">
                                        <input type="hidden" name="userName" id="userName" value="' . $view->user->getUserName() . '" required>
                                        <div class="input-field col s12 l12">
                                        <input type="text" name="firstName" id="firstName" value="' . $view->user->getFirstName() . '" required>
                                        <label for="firstName">First name</label>
                                        </div><br/>
    
                                        <div class="input-field col s12 l12">
                                        <input type="text" name="lastName" id="lastName" value="' . $view->user->getLastName() . '" required>
                                        <label for="lastName">Last name</label>
                                        </div><br/>
    
                                        <div class="input-field col s12 l12">
                                        <input type="text" name="email" id="email" value="' . $view->user->getEmail() . '" required>
                                        <label for="email">Email</label>
                                        </div><br/>
    
                                        <div class="input-field col s12 l12">
                                        <div class="col s9 l9">
                                        <p>Class</p>
                                        </div>
                                        <div class="input-field col s3 l3">
                                        <select name="classID" class="browser-default" id="classID">
                                        <option value="None">None (Current)</option>
                                        <option value="None">None (Admin)</option>
                                        ';
                                            foreach ($view->allClasses as $class) {
                                                //Creating an option and showing the class names and sending the class ID to the controller
                                                echo '<option value="' . $view->dataSet->fetchClassID($class) . '">' . $class . '</option>';
                                            }
                                            echo '
                                        </select>
                                        </div>
                                        </div><br/>
        
                                        <div class="input-field col s12 l12">
                                        <input type="password" name="password" id="password" required>
                                        <label for="password">New Password</label>
                                        </div><br/>
        
                                        
                                        <div class="right btn-block col s12 l12">
                                        <input class="btn black right z-depth-2" type="submit"
                                        name="submit" value="Edit User">
                                        </div>
                                        </form>
                                        ';

                                    }
                                    else {
                                            echo '<h6 class="center helper-text">User not found</h6>';
                                    }
                                }
                                else{
                                    echo '
                                        <form name="addUser" method="post" action="' . $_SERVER['PHP_SELF'] . '">
                                        <input type="hidden" name="userName" id="userName" value="' . $view->user->getUserName() . '" required>
                                        <div class="input-field col s12 l12">
                                        <input type="text" name="firstName" id="firstName" value="' . $view->user->getFirstName() . '" required>
                                        <label for="firstName">First name</label>
                                        </div><br/>
    
                                        <div class="input-field col s12 l12">
                                        <input type="text" name="lastName" id="lastName" value="' . $view->user->getLastName() . '" required>
                                        <label for="lastName">Last name</label>
                                        </div><br/>
    
                                        <div class="input-field col s12 l12">
                                        <input type="text" name="email" id="email" value="' . $view->user->getEmail() . '" required>
                                        <label for="email">Email</label>
                                        </div><br/>
    
                                        <div class="input-field col s12 l12">
                                        <div class="col s9 l9">
                                        <p>Class</p>
                                        </div>
                                        <div class="input-field col s3 l3">
                                        <select name="classID" class="browser-default" id="classID">';

                                        if ($view->user->getRoleID()==2 || $view->user->getRoleID()==3)
                                        {
                                            echo '<option value="' . $view->user->getClassID() .'">' . $view->dataSet->fetchClassName($view->user->getClassID()).' (Current)</option>';
                                        }
                                        else
                                        {
                                            echo '<option value="None">None (Current)</option>';
                                        }

                                    echo '
                                        <option value="None">None (Admin)</option>
                                        ';
                                    foreach ($view->allClasses as $class) {
                                        //Creating an option and showing the class names and sending the class ID to the controller
                                        echo '<option value="' . $view->dataSet->fetchClassID($class) . '">' . $class . '</option>';
                                    }
                                    echo '
                                        </select>
                                        </div>
                                        </div><br/>
        
                                        <div class="input-field col s12 l12">
                                        <input type="password" name="password" id="password">
                                        <label for="password">New Password</label>
                                        </div><br/>
        
                                        
                                        <div class="right btn-block col s12 l12">
                                        <input class="btn black right z-depth-2" type="submit"
                                        name="submit" value="Edit User">
                                        </div>
                                        </form>
                                        ';
                                }
                            }
                            else
                            {
                                echo '<h6 class="center helper-text">User not found</h6>';
                            }
                        }
                        else
                        {
                            echo '<h6 class="center helper-text">User not found</h6>';
                        }
                    }

                    ?>
                    <div>
                        <p class="red-text"><?php if(isset($view->errorMessage)){ echo $view->errorMessage; } ?></p>
                        <p><?php if(isset($view->editUserSuccess)){ echo $view->editUserSuccess; } ?></p>
                    </div>
                </div>
        </div>
    </div>
</div>
<?php require('template/footer.phtml') ?>
