<?php require('template/header.phtml') ?>
<div class="container row" id="admin-container">
    <div class="container s12 l12" id="ls-header">
    </div>

    <div class="row">
        <div class="col s12">
            <div id="test1" class="col s12">
                <div class="container">
                    <form name="addUser" method="post" action="<?php echo $_SERVER['PHP_SELF']; ?>">
                        <div class="input-field col s12 l12">
                            <input type="text" name="userName" id="userName" value="<?php if (isset($view->errorMessage)){echo $_POST['userName'];} ?>" required>
                            <label for="userName">Username</label>
                        </div><br/>

                        <div class="right btn-block col s12 l12">
                            <input class="btn black right z-depth-2" type="submit" name="searchUser" value="Edit User">
                        </div>
                    </form>
                </div>

                <div class="container">
                    <?php
                    if (isset($view->allUsers))
                    {
                        echo'
                        <form name="addUser" method="post" action="' . $_SERVER['PHP_SELF'] . '">
                            <div class="input-field col s12 l12">
                                <input type="text" name="userName" id="userName" value="<?php if (isset($view->errorMessage)){echo $_POST[\'userName\'];}?>" required>
                                <label for="userName">Username</label>
                            </div><br/>

                            <div class="input-field col s12 l12">
                                <input type="text" name="firstName" id="firstName" value="<?php if (isset($view->errorMessage)){echo $_POST[\'firstName\'];}?>" required>
                                <label for="firstName">Firstname</label>
                            </div><br/>

                            <div class="input-field col s12 l12">
                                <input type="text" name="lastName" id="lastName" value="<?php if (isset($view->errorMessage)){echo $_POST[\'lastName\'];}?>" required>
                                <label for="lastName">Lastname</label>
                            </div><br/>

                            <div class="input-field col s12 l12">
                                <input type="text" name="email" id="email" value="<?php if (isset($view->errorMessage)){echo $_POST[\'email\'];}?>" required>
                                <label for="email">Email</label>
                            </div><br/>

                            <div class="input-field col s12 l12">
                             <div class="col s9 l9">
                                <p>Class</p>
                            </div>
                            <div class="input-field col s3 l3">
                            <select name="classID" class="browser-default" id="classID">
                            <option value="None">None (Admin)</option>
                        ';
                        foreach ($view->allClasses as $class) {
                            //Creating an option and showing the class names and sending the class ID to the controller
                            echo '<option value="' . $view->dataSet->fetchClassID($class) . '">' . $class . '</option>';
                        }
                        echo '
                    </select>
                </div>
            </div><br/>

            <div class="input-field col s12 l12">
                <input type="password" name="password" id="password" required>
                <label for="password">Password</label>
            </div><br/>

            <div class="right btn-block col s12 l12">
                <input class="btn black right z-depth-2" type="submit"
                       name="submit" value="Create User">
            </div>
        </form>
                        ';
                    }
                    ?>
                </div>
        </div>
    </div>
</div>
<?php require('template/footer.phtml') ?>
