<?php require('template/header.phtml') ?>
<div class="container row" id="admin-container">
    <div class="container s12 l12" id="ls-header">
        <h6 class="center black-text"><strong>Home</strong></h6>
    </div>

    <div class="container row">
        <div class="container col s12 l12 black-text">
            <ul class="collection with-header blue-grey z-depth-2">
                <li class="collection-header z-depth-2 center"><h6><strong>Outstanding Rubrics</strong></h6></li>

            </ul>
        </div>
    </div>
</div>
<?php require('template/footer.phtml') ?>
