<?php require('template/header.phtml') ?>
    <div class="container s12 l12" id="ls-header">
        <h6 class="center helper-text"><strong>Name: <?php echo $view->user->getFirstName() . ' ' . $view->user->getLastName()?></strong></h6>
    </div>
    <div class="container s12 l12" id="ls-header">
        <h6 class="center helper-text"><strong>Test: Index</strong></h6>
    </div>
<?php require('template/footer.phtml') ?>
