<?php require('template/header.phtml') ?>
<div class="container s12 l12" id="ls-header">
    <h6 class="center helper-text"><strong>Test: rubricEditor</strong></h6>
</div>
<div class="container row s12 l12 rubric-admin">
    <div class="container col s12 l12">
        <form name="studentFill" method="post" action="<?php echo $_SERVER['PHP_SELF'];?>">
            <?php
            var_dump($view->rubricsInfo);
            var_dump($view->newRubricsInfo);
            ?>
        </form>
    </div>
</div>
<?php require('template/footer.phtml') ?>
