<?php require('template/header.phtml') ?>
<div class="container row s12 l12 rubric-admin">
    <div class="container col s12 l12">
        <form name="studentFill" method="post" action="<?php echo $_SERVER['PHP_SELF'];?>">
            <?php

            $rubricCount = 0;
            foreach($view->twoRubricsInfo as $array)
            {

                $arrayTemp = $array;
                $rubricName = array_shift($arrayTemp);

                echo "<div class=\"container s12 l12\" id=\"ls-header\">
              <h6 class=\"center helper-text\"><strong>{$rubricName}</strong></h6></div>";
                echo "<table class=\"fixed\"><tbody>";

                $arrayTempChunked = array_chunk($arrayTemp, $_SESSION['criteria_count']+1);

                $radioBtnGroup = 1;
                foreach($arrayTempChunked as $arrayCC)
                {
                    echo "<tr>";
                    $arrayTempCC = $arrayCC;
                    $categoryName = array_shift($arrayTempCC);


                    // echo $categoryName;

                    echo "<td>{$categoryName}</td>";

                    $valueCount = 1;

                    foreach ($arrayTempCC as $key => $value)
                    {
                        echo "<td>{$value}</td>";
                        echo "<td>
                              <label>
                              <input class=\"with-gap\" type=\"radio\" value=\"{$valueCount}\" name=\"{$rubricName}{$radioBtnGroup}\"/> 
                              <span></span>
                              </label>
                              </td>";
                        $valueCount++;
                    }
                    $radioBtnGroup++;
                    echo "</tr>";
                    $valueCount = 1;
                }

                echo"</tbody></table><br/>";
                $rubricCount++;
            }
            $radioBtnGroup = 1;
            ?>
            <div class="btn-block col s12 l12">
                <input class="btn black right z-depth-2" type="submit"
                       name="submit" value="Submit">
            </div>
        </form>
    </div>
</div>
<?php require('template/footer.phtml') ?>
