<?php //var_dump($_POS// var_dump($_SESSION);?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">


    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="A Crafting Forum">
    <meta name="author" content="Ali Hassan">

    <!-- Materialize Stylesheet -->
    <link type="text/css" rel="stylesheet" href="/css/materialize.min.css"  media="screen"/>
    <!-- Own Stylesheet -->
    <link href="/css/my-style.css" type="text/css" rel="stylesheet" media="screen"/>
    <!-- Materialize CSS Icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Title of the open tab in a browser -->
    <title>Competa Rubrics - <?php echo $view->pageTitle; ?></title>
</head>
<body>
<!-- Title of the open tab in a browser -->
<header class="nav-content">
    <?php

    if (isset($_SESSION['user']))
    {
        if ($_SESSION['user']->getRoleID() === '1' || $_SESSION['user']->getRoleID() === '2' ) {
            echo '
                <!-- Dropdown Structure -->
                <ul id="dropdown1" class="dropdown-content black">
                    <li><a class=\'btn-block\' href=\'viewUserData.php\'>View User</a></li>
                    <li class="divider"></li>';

                    if ($_SESSION['user']->getRoleID() === '1')
                    {
                        echo '   
                                <li><a class=\'btn-block\' href=\'adminAddUser.php\'>Add User</a></li>
                                <li class="divider"></li>  
                                ';
                    }
                echo '
                    
                    <li><a class=\'btn-block\' href=\'editUser.php\'>Edit User</a></li>
                    <li class="divider"></li>';

                    if ($_SESSION['user']->getRoleID() === '1')
                    {
                        echo '   
                                <li><a class=\'btn-block\' href=\'adminDeleteUser.php\'>Delete User</a></li> 
                                ';
                    }
                echo '
                    
                </ul>
                
                <!-- Dropdown Structure 2 -->
                <ul id="dropdown2" class="dropdown-content black">
                    <li><a class=\'btn-block\' href=\'viewUserData.php\'>View User</a></li>
                    <li class="divider"></li>';

                    if ($_SESSION['user']->getRoleID() === '1')
                    {
                        echo '   
                                <li><a class=\'btn-block\' href=\'adminAddUser.php\'>Add User</a></li>
                                <li class="divider"></li>  
                                ';
                }
            echo '<li><a class=\'btn-block\' href=\'editUser.php\'>Edit User</a></li>
                     <li class="divider"></li>';
                    if ($_SESSION['user']->getRoleID() === '1')
                    {
                        echo '   
                                <li><a class=\'btn-block\' href=\'adminDeleteUser.php\'>Delete User</a></li> 
                                ';
                    }
             echo '        
            </ul>
            
            <!-- Dropdown Structure - Manage Class 1 -->
                <ul id="manageClass1" class="dropdown-content black">
                    <li><a class=\'btn-block\' href=\'assignTableGroup.php\'>Assign Table Group</a></li>
                    <li class="divider"></li>';

                    if ($_SESSION['user']->getRoleID() === '1')
                    {
                        echo '   
                                <li><a class=\'btn-block\' href=\'adminCreateClass.php\'>Create Class</a></li>
                                <li class="divider"></li>
                                <li><a class=\'btn-block\' href=\'adminDeleteClass.php\'>Delete Class</a></li> 
                                ';
                    }
                echo '
                </ul>
                
                <!-- Dropdown Structure - Manage Class 2 -->
                <ul id="manageClass2" class="dropdown-content black">
                    <li><a class=\'btn-block\' href=\'assignTableGroup.php\'>Assign Table Group</a></li>
                    <li class="divider"></li>';

                    if ($_SESSION['user']->getRoleID() === '1')
                    {
                        echo '   
                                <li><a class=\'btn-block\' href=\'adminCreateClass.php\'>Create Class</a></li>
                                <li class="divider"></li>
                                <li><a class=\'btn-block\' href=\'adminDeleteClass.php\'>Delete Class</a></li>
                                ';
                    }
                echo '
                </ul>';


        }
    }

    if(isset($_SESSION['user']))
    {
        echo '<!-- Dropdown Structure 3-->
                     <ul id="dropdown3" class="dropdown-content black">';

        if($_SESSION['user']->getRoleID() === '1')
        {
            echo '<li><a class=\'btn-block\' href=\'adminRubricCreate.php\'>Rubric Generator</a></li>';
        }
        echo '<li class="divider"></li>
                     <li><a class=\'btn-block\' href=\'searchRubric.php\'>Rubric Search</a></li>
                     </ul><li class="divider"></li>';
    }

    if(isset($_SESSION['user']))
    {
        echo '<!-- Dropdown Structure 4-->
                     <ul id="dropdown4" class="dropdown-content black">';

        if($_SESSION['user']->getRoleID() === '1')
        {
            echo '<li><a class=\'btn-block\' href=\'adminRubricCreate.php\'>Rubric Generator</a></li>';
        }
        echo '<li class="divider"></li>
                     <li><a class=\'btn-block\' href=\'searchRubric.php\'>Rubric Search</a></li>
                     </ul><li class="divider"></li>';
    }

    ?>

    <nav class="black">
        <div id="top-nav" class="container nav-wrapper">
            <a href="index.php" class="brand-logo center lighten-3">Rubrics</a>

            <!-- Nav when view is more than 992px -->
            <ul class="left hide-on-med-and-down">
                <?php if(isset($_SESSION['user']))
                {
                    echo "<li><a class='btn-block' href='myData.php'>My Data</a></li>";
                    if($_SESSION['user']->getRoleID() === '1' || $_SESSION['user']->getRoleID() === '2')
                    {
                        echo "<li><a class=\"dropdown-trigger\" href=\"#!\" data-target=\"dropdown1\">Manage User<i class=\"material-icons right\">arrow_drop_down</i></a></li>";
                        echo "<li><a class=\"dropdown-trigger\" href=\"#!\" data-target=\"manageClass1\">Manage Class<i class=\"material-icons right white-text\">arrow_drop_down</i></a></li>";

                    }
                } ?>
            </ul>

            <ul class="right hide-on-med-and-down">
                <?php if(isset($_SESSION['user']))
                {
                    if($_SESSION['user']->getRoleID() == '1' || $_SESSION['user']->getRoleID() == '2' || $_SESSION['user']->getRoleID() === '3')
                    {
                        echo "<li><a class=\"dropdown-trigger\" href=\"#!\" data-target=\"dropdown3\">Manage Rubrics<i class=\"material-icons right\">arrow_drop_down</i></a></li>";
                    }
                    echo "<li><a href='../../logout.php'>Log Out</a></li>";
                }
                else{
                    // Used to trigger my modal login form
                    echo "<li><a href='index.php'>Login</a></li>";
                }
                ?>
            </ul>

            <!-- Sidenav when view is v>992px  -->
            <ul id="slide-out" class="sidenav black">
                <?php if(isset($_SESSION['user']))
                {
                    echo "<li><a class='btn-block' href='myData.php'>My Data</a></li><li class=\"divider\"></li>  ";

                    if($_SESSION['user']->getRoleID() === '1' || $_SESSION['user']->getRoleID() === '2')
                    {
                        echo "<li><a class=\"dropdown-trigger\" href=\"#!\" data-target=\"dropdown2\">Manage User<i class=\"material-icons right white-text\">arrow_drop_down</i></a></li>";
                        echo "<li><a class=\"dropdown-trigger\" href=\"#!\" data-target=\"manageClass2\">Manage Class<i class=\"material-icons right white-text\">arrow_drop_down</i></a></li>";
                    }
                    echo "<li><a class=\"dropdown-trigger\" href=\"#!\" data-target=\"dropdown4\">Manage Rubrics<i class=\"material-icons right white-text\">arrow_drop_down</i></a></li><li class=\"divider\"></li>  ";
                    echo "<li><a class='btn-block' href='../../logout.php'> Log Out</a></li>";
                }
                else{
                    echo "<li><a href='login.php'>Login</a></li>";
                }
                ?>
            </ul>

            <!-- Use of materialise sidenav for v<992px navigation -->
            <a href="#" data-target="slide-out" class="sidenav-trigger right">
                <i class="material-icons">menu</i></a>
        </div>
    </nav>
</header>
<!-- Incomplete starting div tag to be completed through a php stitch with footer -->
<main>
